### ISSUE TITLE
review and test scroll messaging system and fix potential issues

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#15]

**Comment by kateberryd** [comment]
Hi

**Comment by ooochoche** [comment]
@dragan2234 I can handle this

**Comment by Jemiiah** [comment]
i would loce to work on this @dragan2234

**Comment by Oshioke-Salaki** [comment]
can i work on this please? This wopuld be my first time contributing

**Comment by ShantelPeters** [comment]
Please I will love to work on this issue @dragan2234
