### ISSUE TITLE
investigate on native L1(ethereum)<>L2(scroll) data messaging layer

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#2]
Investigate, and document how is this done with Scroll L2

**Comment by kamalbuilds** [comment]
Hi @dragan2234 , looking to pick this up.

**Comment by MayowaObisesan** [comment]
Hi @dragan2234 . I'll like to take up this issue.

**Comment by MayowaObisesan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-scroll-bridge).

### My background and how it can be leveraged
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged
I am a web3 developer (smart contract and frontend) with knowledge working and building on various blockchains. I participated in the just concluded scroll 2024 hackathon and won in multiple tracks. I believe that this helps my understanding of the scroll blockchain.


### How I plan on tackling this issue
My first approach is to use the scroll docs to find the answers to this issue. My secondary approach is to then do more research about the messaging layer and write my findings on this.

**Comment by MayowaObisesan** [comment]
Hey @dragan2234 .
I'm done with my research and documentation. Which folder is my readme supposed to be in?

**Comment by dragan2234** [comment]
@MayowaObisesan hey can you add the DATA_MESSAGE_LAYER_RESEARCH.md file with your docs?
