### ISSUE TITLE
Ensure that the scroll bridge is working

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#20]
Also fix the deployment script (deploy-testnet) so it deploys ScrollBridge on Eth sepolia instead of Scroll sepolia

**Comment by Naomi-Gift** [comment]
@dragan2234 can I work on this?

I’ll ensure I fix the deployment scripts

**Comment by ShantelPeters** [comment]
Hi @dragan2234 please can I be assigned to this issue?

**Comment by DevPelz** [comment]
Hello @dragan2234 Can i take this up. Id love to work on it

**Comment by Ugo-X** [comment]
@dragan2234 can I be assigned this please?
