### ISSUE TITLE
Implement Mock smart contracts (MockScrollBridge, MockScrollWorldID, MockWorldIDIdentityManager...)

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#27]
Implement mock smart contracts for testing the workflow locally. Add the docs on how to test it properly.

Some of the contracts are there (src/mock) but it's still not working properly.

**Comment by od-hunter** [comment]
Can I work on this please @dragan2234 ?

**Comment by ikemHood** [comment]
Hh

**Comment by ShantelPeters** [comment]
Please can I take this up @dragan2234

**Comment by Ugo-X** [comment]
Good afternoon @dragan2234. Please can I be assigned this issue. I will be sure to implement the mock contracts to test the workflow locally and provide adequate documentation on how to test it properly

**Comment by ikemHood** [comment]
Hello @dragan2234, I am available and would love to work on this.
ETA: 24hrs
