### ISSUE TITLE
Implement test for ScrollWorldID

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#28]
Analogue to this:

https://github.com/worldcoin/world-id-state-bridge/blob/main/src/test/OpWorldID.t.sol

**Comment by ikemHood** [comment]
Hello @dragan2234, I would love to work on this

**Comment by Naomi-Gift** [comment]
@dragan2234 can I work on this?

**Comment by Jemiiah** [comment]
I would love to work on this issue @dragan2234
