### ISSUE TITLE
Ensure deploy scripts are properly working for Scroll World ID

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#30]

**Comment by ShantelPeters** [comment]
Hi @dragan2234 can i please be assigned to this issue ?

**Comment by Jemiiah** [comment]
If this issue would be open for open source contributions would love to work on it

**Comment by Ugo-X** [comment]
Good afternoon @dragan2234 Please can i be assigned to this issue
