### ISSUE TITLE
sync the code from original worldcoin repo

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#32]
https://github.com/worldcoin/world-id-state-bridge/tree/dcbuild3r/scroll

**Comment by od-hunter** [comment]
Hi @dragan2234 Please let me work on this

**Comment by ShantelPeters** [comment]
Can I work on this @dragan2234

**Comment by Ugo-X** [comment]
Hello @dragan2234  Please can i be assigned to this?
