### ISSUE TITLE
create a service to sync the World ID merkle tree

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#9]
Based on docs from here:
https://github.com/dragan2234/worldcoin-scroll-bridge/tree/main/service-to-sync-the-World-ID-merkle-tree-main

**Comment by Ugo-X** [comment]
@dragan2234  Please can I be assigned this?

**Comment by dragan2234** [comment]
hey @Ugo-X did you make any progress?

**Comment by Ugo-X** [comment]
> hey @Ugo-X did you make any progress?

Hello!! Yes, I had to do some further research, I will send a PR before the week runs out.

**Comment by Ugo-X** [comment]
@dragan2234 Good morning, for the Purpose of clarification, what BlockChain are we building this bridging contract on?

**Comment by dragan2234** [comment]
Hi, @Ugo-X I'm not sure that i understand your question. Maybe this description helps:

> The point of the state bridge contracts in world-id-state-bridge is to have two contracts, one deployed on Ethereum mainnet and the other one on a target L2. The mainnet contract (e.g. OpStateBridge) has a public function which will fetch the latest root of the World ID merkle tree using the [WorldIDIdentityManagerImplV1](https://github.com/worldcoin/world-id-contracts/blob/main/src/WorldIDIdentityManagerImplV1.sol) method named [latestRoot()](https://github.com/worldcoin/world-id-contracts/blob/42c26ecbd82fba56983addee6485d5b617960a2a/src/WorldIDIdentityManagerImplV1.sol#L433-L438) and then will use the native L1<>L2 messaging layer to send a message to the target L2 contract (e.g. OpWorldID). The messaging layer of the L2 will forward the message to the target contract by calling the corresponding method on the L2 contract with the specified payload from the L1.


So both Ethereum mainnet and Scroll (the above example explains how it's done with Optimism).

**Comment by Ugo-X** [comment]
> Hi, @Ugo-X I'm not sure that i understand your question. Maybe this description helps:
> 
> > The point of the state bridge contracts in world-id-state-bridge is to have two contracts, one deployed on Ethereum mainnet and the other one on a target L2. The mainnet contract (e.g. OpStateBridge) has a public function which will fetch the latest root of the World ID merkle tree using the [WorldIDIdentityManagerImplV1](https://github.com/worldcoin/world-id-contracts/blob/main/src/WorldIDIdentityManagerImplV1.sol) method named [latestRoot()](https://github.com/worldcoin/world-id-contracts/blob/42c26ecbd82fba56983addee6485d5b617960a2a/src/WorldIDIdentityManagerImplV1.sol#L433-L438) and then will use the native L1<>L2 messaging layer to send a message to the target L2 contract (e.g. OpWorldID). The messaging layer of the L2 will forward the message to the target contract by calling the corresponding method on the L2 contract with the specified payload from the L1.
> 
> So both Ethereum mainnet and Scroll (the above example explains how it's done with Optimism).

alright, thank you, this answers my question.

**Comment by Ugo-X** [comment]
@dragan2234 Good afternoon Chief, I will be sending a PR shortly, with Documentation on how to set it up.

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this issue
